### ISSUE TITLE
feat: studio TUI

### ISSUE THREAD

**Issue by tulilirockz** [atomic-studio-org/studio-cli#7]
Maybe we could implement a TUI thing for this. Fig used to exist for that but now yeah thats not an option. To not need an entire new implementation of this CLI thing, we could create a new project that parses a JSON file with a manifest for this CLI app, it would be something using this schema:

```yaml
---
name: string # Required
pname: string # Required
commands: # Optional
  - name: string # Required
    description: string # Optional
    arguments: # Optional
      - name: string
        type: string
```
